### ISSUE TITLE
YouTube add-on integration

### ISSUE THREAD

**Issue by anxdpanic** [evantaur/plugin.youtube2kodilibrary#1]
This isn't really an issue/request.
It's not widely used and known about, but you can (optionally) use the YouTube add-on as a module. You'll be able to use the add-on to retrieve the results using the users existing YouTube set up (api keys/sign in credentials).

https://github.com/jdf76/plugin.video.youtube/blob/master/changelog.txt#L400

The ones you might be interested in:
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_requests.py
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_resolver.py

There is also a couple more if you want to handle passing keys and handling login stuff:
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_registration.py
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_authentication.py

btw 
https://github.com/evantaur/plugin.youtube2kodilibrary/blob/master/addon.py#L190-L203
can be simplified to:
```python
def __check_if_youtube_addon_has_api_key():
    try:
        api_key = xbmcaddon.Addon('plugin.video.youtube').getSetting('youtube.api.key')
    except RuntimeError:
        # YouTube add-on isn't installed
        api_key = ''

    if not api_key:
        return None
		
    response = xbmcgui.Dialog().yesno(addonname, 'Would you like to use the same API key you have set on YouTube addon?')

    if response:
        return api_key
	
    return None
```

Hope the information helps,
Cheers

**Comment by evantaur** [comment]
thanks, that xbmcaddon.Addon('plugin.video.youtube').getSetting('youtube.api.key') was exactly what i was looking for :) (always hated XML)
