### ISSUE TITLE
Replacement for YouTube Kodi addon?

### ISSUE THREAD

**Issue by leopheard** [evantaur/plugin.youtube2kodilibrary#3]
Can this replace the main YouTube addon? What does this do differently? My current YouTube addon won't show watched later, playlists etc on my YT account any more.

**Comment by evantaur** [comment]
No this can't. It simply imports youtube channels to the library so you can watch them like TV-shows using the actual youtube addon.

**Comment by evantaur** [comment]
If you're using KODI v19 (Matrix) you could try an addon called "tubed", it's in the official repo and I'll be adding support for it in an upcoming update.
