### ISSUE TITLE
Possible to support channels with >50 playlists?

### ISSUE THREAD

**Issue by Insight-Rich** [evantaur/plugin.youtube2kodilibrary#4]
Nice work, and seems to be the closest add-on to what I'm looking for (trying to surface specific playlists for my son without him being able to dig around in the murky depths of YouTube), but there's just one snag: the channel I'm looking at ([MrZebraGamer](https://www.youtube.com/user/MrZebraGamer)) has over 300 playlists, and current code uses a single playlist.list call returning a max of 50.

I haven't coded in anger in years, and never really touched Python before, but it looks like the 'plugin.video.youtube' add-on pulls in a full list iteratively using [get_playlists_of_channel](https://github.com/anxdpanic/plugin.video.youtube/blob/9942eaff0ea7104ea7c3b149c2a281380cb07168/resources/lib/youtube_requests.py#L226):

```python
    items = []

    def get_items(_page_token=''):
        json_data = client.get_playlists_of_channel(channel_id, page_token=_page_token)
        if not handle_error(context, json_data):
            return [json_data]

        for item in json_data.get('items', []):
            items.append(item)

        next_page_token = json_data.get('nextPageToken')
        if all_pages and (next_page_token is not None):
            get_items(_page_token=next_page_token)
        elif next_page_token is not None:
            items.append({'nextPageToken': next_page_token})

    get_items(_page_token=page_token)

    items = _append_missing_page_token(items)

    return items
```

Probably a fairly niche use-case, so no worries if it's not something that's a priority.  Might even give me the kick I need to learn how to use GitHub for more than just being nosy ... =]

**Comment by evantaur** [comment]
I'll look into it next week, thanks for including the youtube example.

**Comment by evantaur** [comment]
Added this feature, and it'll be in the next version.
